### ISSUE TITLE
login in the st-frontend

### ISSUE THREAD

**Issue by Saibo-creator** [derlin/swisstext#1]
Hello, could you point out what should I use for name and password in the login interface of the frontend ? It seems not to be the username and password of MongoDB.

![image](https://user-images.githubusercontent.com/53392976/86759911-2092f600-c045-11ea-8be5-4f79d0682d11.png)

**Comment by derlin** [comment]
This is a very good point, I forgot to mention it. You need to add a user to the `users` collection in mongodb, for example:
```js
db.users.insert({"_id": "username", "password": hex_md5("some_password"), "roles": [ "admin" ]});
```

**Comment by Saibo-creator** [comment]
Thanks for your explanation!
